version: '3.5'

services:

  mysql-master:
    image: mysql/mysql-server:8.0
    container_name: mysql-master
    hostname: mysql-master
    ports:
      - '1441:3306'
    restart: always
    # sets the network address which the member provides for connections from other members, specified as a host:port formatted string.
    command: [ "mysqld", "--loose-group-replication-local-address=mysql-master:6606" ]
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: n9e_1234
      MYSQL_DATABASE: n9e_v6
    volumes:
      - /usr/local/mysql/master/data:/var/lib/mysql/
      - ./configs/my-cnf:/etc/mysql/my.cnf
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      interval: 2s
      retries: 20

  mysql-slave1:
    image: mysql/mysql-server:8.0
    container_name: mysql-slave1
    hostname: mysql-slave1
    ports:
      - '1442:3306'
    restart: always
    # sets the network address which the member provides for connections from other members, specified as a host:port formatted string.
    command: [ "mysqld", "--loose-group-replication-local-address=mysql-slave1:6606" ]
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: n9e_1234
      MYSQL_DATABASE: n9e_v6
    volumes:
      - /usr/local/mysql/slave1/data:/var/lib/mysql/
      - ./configs/my-cnf-slave1:/etc/mysql/my.cnf
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      interval: 2s
      retries: 20

  mysql-slave2:
    image: mysql/mysql-server:8.0
    container_name: mysql-slave2
    hostname: mysql-slave2
    ports:
      - '1443:3306'
    restart: unless-stopped
    # sets the network address which the member provides for connections from other members, specified as a host:port formatted string.
    command: [ "mysqld", "--loose-group-replication-local-address=mysql-slave2:6606" ]
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: n9e_1234
      MYSQL_DATABASE: n9e_v6
    volumes:
      - /usr/local/mysql/slave2/data:/var/lib/mysql/
      - ./configs/my-cnf-slave2:/etc/mysql/my.cnf
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      interval: 2s
      retries: 20
